/**
 * By default, Remix will handle hydrating your app on the client for you.
 * You are free to delete this file if you'd like to, but if you ever want it revealed again, you can run `npx remix reveal` ✨
 * For more information, see https://remix.run/file-conventions/entry.client
 */

import { RemixBrowser } from "@remix-run/react";
import { startTransition, StrictMode } from "react";
import { hydrateRoot } from "react-dom/client";

startTransition(() => {
  hydrateRoot(
    document,
    <StrictMode>
      <RemixBrowser />
    </StrictMode>
  );
});
// This file is the entry point for client-side rendering in a Remix application.
// It uses React's `hydrateRoot` to attach the React application to the server-rendered HTML.
// The `StrictMode` wrapper is used to help identify potential problems in the application.
// The `startTransition` function is used to mark the hydration as a low-priority update, allowing the browser to remain responsive during the process.
// This setup is essential for enabling client-side navigation and interactivity in a Remix app.
// This file is automatically generated by Remix and should not be modified directly.
// It is used to bootstrap the client-side application after the server has rendered the initial HTML.
// The `RemixBrowser` component is the root component for the Remix application, which handles routing and rendering of pages.
